// Generated by gencpp from file cyberglove/Calibration.msg
// DO NOT EDIT!


#ifndef CYBERGLOVE_MESSAGE_CALIBRATION_H
#define CYBERGLOVE_MESSAGE_CALIBRATION_H

#include <ros/service_traits.h>


#include <cyberglove/CalibrationRequest.h>
#include <cyberglove/CalibrationResponse.h>


namespace cyberglove
{

struct Calibration
{

typedef CalibrationRequest Request;
typedef CalibrationResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Calibration
} // namespace cyberglove


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::cyberglove::Calibration > {
  static const char* value()
  {
    return "511f6c2530f3a6205ada1f7624754c20";
  }

  static const char* value(const ::cyberglove::Calibration&) { return value(); }
};

template<>
struct DataType< ::cyberglove::Calibration > {
  static const char* value()
  {
    return "cyberglove/Calibration";
  }

  static const char* value(const ::cyberglove::Calibration&) { return value(); }
};


// service_traits::MD5Sum< ::cyberglove::CalibrationRequest> should match 
// service_traits::MD5Sum< ::cyberglove::Calibration > 
template<>
struct MD5Sum< ::cyberglove::CalibrationRequest>
{
  static const char* value()
  {
    return MD5Sum< ::cyberglove::Calibration >::value();
  }
  static const char* value(const ::cyberglove::CalibrationRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::cyberglove::CalibrationRequest> should match 
// service_traits::DataType< ::cyberglove::Calibration > 
template<>
struct DataType< ::cyberglove::CalibrationRequest>
{
  static const char* value()
  {
    return DataType< ::cyberglove::Calibration >::value();
  }
  static const char* value(const ::cyberglove::CalibrationRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::cyberglove::CalibrationResponse> should match 
// service_traits::MD5Sum< ::cyberglove::Calibration > 
template<>
struct MD5Sum< ::cyberglove::CalibrationResponse>
{
  static const char* value()
  {
    return MD5Sum< ::cyberglove::Calibration >::value();
  }
  static const char* value(const ::cyberglove::CalibrationResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::cyberglove::CalibrationResponse> should match 
// service_traits::DataType< ::cyberglove::Calibration > 
template<>
struct DataType< ::cyberglove::CalibrationResponse>
{
  static const char* value()
  {
    return DataType< ::cyberglove::Calibration >::value();
  }
  static const char* value(const ::cyberglove::CalibrationResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CYBERGLOVE_MESSAGE_CALIBRATION_H
