// Generated by gencpp from file cyberglove/Start.msg
// DO NOT EDIT!


#ifndef CYBERGLOVE_MESSAGE_START_H
#define CYBERGLOVE_MESSAGE_START_H

#include <ros/service_traits.h>


#include <cyberglove/StartRequest.h>
#include <cyberglove/StartResponse.h>


namespace cyberglove
{

struct Start
{

typedef StartRequest Request;
typedef StartResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Start
} // namespace cyberglove


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::cyberglove::Start > {
  static const char* value()
  {
    return "749d251204872700c0771978d6a77944";
  }

  static const char* value(const ::cyberglove::Start&) { return value(); }
};

template<>
struct DataType< ::cyberglove::Start > {
  static const char* value()
  {
    return "cyberglove/Start";
  }

  static const char* value(const ::cyberglove::Start&) { return value(); }
};


// service_traits::MD5Sum< ::cyberglove::StartRequest> should match 
// service_traits::MD5Sum< ::cyberglove::Start > 
template<>
struct MD5Sum< ::cyberglove::StartRequest>
{
  static const char* value()
  {
    return MD5Sum< ::cyberglove::Start >::value();
  }
  static const char* value(const ::cyberglove::StartRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::cyberglove::StartRequest> should match 
// service_traits::DataType< ::cyberglove::Start > 
template<>
struct DataType< ::cyberglove::StartRequest>
{
  static const char* value()
  {
    return DataType< ::cyberglove::Start >::value();
  }
  static const char* value(const ::cyberglove::StartRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::cyberglove::StartResponse> should match 
// service_traits::MD5Sum< ::cyberglove::Start > 
template<>
struct MD5Sum< ::cyberglove::StartResponse>
{
  static const char* value()
  {
    return MD5Sum< ::cyberglove::Start >::value();
  }
  static const char* value(const ::cyberglove::StartResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::cyberglove::StartResponse> should match 
// service_traits::DataType< ::cyberglove::Start > 
template<>
struct DataType< ::cyberglove::StartResponse>
{
  static const char* value()
  {
    return DataType< ::cyberglove::Start >::value();
  }
  static const char* value(const ::cyberglove::StartResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CYBERGLOVE_MESSAGE_START_H
