// Generated by gencpp from file phidgets/accelerometer_params.msg
// DO NOT EDIT!


#ifndef PHIDGETS_MESSAGE_ACCELEROMETER_PARAMS_H
#define PHIDGETS_MESSAGE_ACCELEROMETER_PARAMS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace phidgets
{
template <class ContainerAllocator>
struct accelerometer_params_
{
  typedef accelerometer_params_<ContainerAllocator> Type;

  accelerometer_params_()
    : header()
    , acceleration()
    , orientation()
    , stamp()  {
    }
  accelerometer_params_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , acceleration(_alloc)
    , orientation(_alloc)
    , stamp(_alloc)  {
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _acceleration_type;
  _acceleration_type acceleration;

   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _orientation_type;
  _orientation_type orientation;

   typedef std::vector<ros::Time, typename ContainerAllocator::template rebind<ros::Time>::other >  _stamp_type;
  _stamp_type stamp;




  typedef boost::shared_ptr< ::phidgets::accelerometer_params_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::phidgets::accelerometer_params_<ContainerAllocator> const> ConstPtr;

}; // struct accelerometer_params_

typedef ::phidgets::accelerometer_params_<std::allocator<void> > accelerometer_params;

typedef boost::shared_ptr< ::phidgets::accelerometer_params > accelerometer_paramsPtr;
typedef boost::shared_ptr< ::phidgets::accelerometer_params const> accelerometer_paramsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::phidgets::accelerometer_params_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::phidgets::accelerometer_params_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace phidgets

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'nav_msgs': ['/opt/ros/indigo/share/nav_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/indigo/share/sensor_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/indigo/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'move_base_msgs': ['/opt/ros/indigo/share/move_base_msgs/cmake/../msg'], 'phidgets': ['/home/jayme/workspace/dextrus_ws/src/phidgets/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::phidgets::accelerometer_params_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::phidgets::accelerometer_params_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::phidgets::accelerometer_params_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::phidgets::accelerometer_params_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::phidgets::accelerometer_params_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::phidgets::accelerometer_params_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::phidgets::accelerometer_params_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e2df6f0c8bfad509d688e1e12caabe0d";
  }

  static const char* value(const ::phidgets::accelerometer_params_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe2df6f0c8bfad509ULL;
  static const uint64_t static_value2 = 0xd688e1e12caabe0dULL;
};

template<class ContainerAllocator>
struct DataType< ::phidgets::accelerometer_params_<ContainerAllocator> >
{
  static const char* value()
  {
    return "phidgets/accelerometer_params";
  }

  static const char* value(const ::phidgets::accelerometer_params_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::phidgets::accelerometer_params_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
float64[] acceleration\n\
float64[] orientation\n\
time[] stamp\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::phidgets::accelerometer_params_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::phidgets::accelerometer_params_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.acceleration);
      stream.next(m.orientation);
      stream.next(m.stamp);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct accelerometer_params_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::phidgets::accelerometer_params_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::phidgets::accelerometer_params_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "acceleration[]" << std::endl;
    for (size_t i = 0; i < v.acceleration.size(); ++i)
    {
      s << indent << "  acceleration[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.acceleration[i]);
    }
    s << indent << "orientation[]" << std::endl;
    for (size_t i = 0; i < v.orientation.size(); ++i)
    {
      s << indent << "  orientation[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.orientation[i]);
    }
    s << indent << "stamp[]" << std::endl;
    for (size_t i = 0; i < v.stamp.size(); ++i)
    {
      s << indent << "  stamp[" << i << "]: ";
      Printer<ros::Time>::stream(s, indent + "  ", v.stamp[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // PHIDGETS_MESSAGE_ACCELEROMETER_PARAMS_H
