// Generated by gencpp from file phidgets/manager_params.msg
// DO NOT EDIT!


#ifndef PHIDGETS_MESSAGE_MANAGER_PARAMS_H
#define PHIDGETS_MESSAGE_MANAGER_PARAMS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <std_msgs/String.h>

namespace phidgets
{
template <class ContainerAllocator>
struct manager_params_
{
  typedef manager_params_<ContainerAllocator> Type;

  manager_params_()
    : header()
    , attached(false)
    , name()
    , serial(0)
    , device_class(0)
    , device_id(0)
    , version(0)  {
    }
  manager_params_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , attached(false)
    , name(_alloc)
    , serial(0)
    , device_class(0)
    , device_id(0)
    , version(0)  {
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint8_t _attached_type;
  _attached_type attached;

   typedef  ::std_msgs::String_<ContainerAllocator>  _name_type;
  _name_type name;

   typedef int32_t _serial_type;
  _serial_type serial;

   typedef int32_t _device_class_type;
  _device_class_type device_class;

   typedef int32_t _device_id_type;
  _device_id_type device_id;

   typedef int32_t _version_type;
  _version_type version;




  typedef boost::shared_ptr< ::phidgets::manager_params_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::phidgets::manager_params_<ContainerAllocator> const> ConstPtr;

}; // struct manager_params_

typedef ::phidgets::manager_params_<std::allocator<void> > manager_params;

typedef boost::shared_ptr< ::phidgets::manager_params > manager_paramsPtr;
typedef boost::shared_ptr< ::phidgets::manager_params const> manager_paramsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::phidgets::manager_params_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::phidgets::manager_params_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace phidgets

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'nav_msgs': ['/opt/ros/indigo/share/nav_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/indigo/share/sensor_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/indigo/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'move_base_msgs': ['/opt/ros/indigo/share/move_base_msgs/cmake/../msg'], 'phidgets': ['/home/jayme/workspace/dextrus_ws/src/phidgets/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::phidgets::manager_params_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::phidgets::manager_params_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::phidgets::manager_params_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::phidgets::manager_params_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::phidgets::manager_params_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::phidgets::manager_params_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::phidgets::manager_params_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5af5478c0ef338e575359b515492c3c1";
  }

  static const char* value(const ::phidgets::manager_params_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5af5478c0ef338e5ULL;
  static const uint64_t static_value2 = 0x75359b515492c3c1ULL;
};

template<class ContainerAllocator>
struct DataType< ::phidgets::manager_params_<ContainerAllocator> >
{
  static const char* value()
  {
    return "phidgets/manager_params";
  }

  static const char* value(const ::phidgets::manager_params_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::phidgets::manager_params_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
bool attached\n\
std_msgs/String name\n\
int32 serial\n\
int32 device_class\n\
int32 device_id\n\
int32 version\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: std_msgs/String\n\
string data\n\
";
  }

  static const char* value(const ::phidgets::manager_params_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::phidgets::manager_params_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.attached);
      stream.next(m.name);
      stream.next(m.serial);
      stream.next(m.device_class);
      stream.next(m.device_id);
      stream.next(m.version);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct manager_params_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::phidgets::manager_params_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::phidgets::manager_params_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "attached: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.attached);
    s << indent << "name: ";
    s << std::endl;
    Printer< ::std_msgs::String_<ContainerAllocator> >::stream(s, indent + "  ", v.name);
    s << indent << "serial: ";
    Printer<int32_t>::stream(s, indent + "  ", v.serial);
    s << indent << "device_class: ";
    Printer<int32_t>::stream(s, indent + "  ", v.device_class);
    s << indent << "device_id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.device_id);
    s << indent << "version: ";
    Printer<int32_t>::stream(s, indent + "  ", v.version);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PHIDGETS_MESSAGE_MANAGER_PARAMS_H
