// Generated by gencpp from file phidgets/servo_reference.msg
// DO NOT EDIT!


#ifndef PHIDGETS_MESSAGE_SERVO_REFERENCE_H
#define PHIDGETS_MESSAGE_SERVO_REFERENCE_H

#include <ros/service_traits.h>


#include <phidgets/servo_referenceRequest.h>
#include <phidgets/servo_referenceResponse.h>


namespace phidgets
{

struct servo_reference
{

typedef servo_referenceRequest Request;
typedef servo_referenceResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct servo_reference
} // namespace phidgets


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::phidgets::servo_reference > {
  static const char* value()
  {
    return "e147971107721d067998f603de281d62";
  }

  static const char* value(const ::phidgets::servo_reference&) { return value(); }
};

template<>
struct DataType< ::phidgets::servo_reference > {
  static const char* value()
  {
    return "phidgets/servo_reference";
  }

  static const char* value(const ::phidgets::servo_reference&) { return value(); }
};


// service_traits::MD5Sum< ::phidgets::servo_referenceRequest> should match 
// service_traits::MD5Sum< ::phidgets::servo_reference > 
template<>
struct MD5Sum< ::phidgets::servo_referenceRequest>
{
  static const char* value()
  {
    return MD5Sum< ::phidgets::servo_reference >::value();
  }
  static const char* value(const ::phidgets::servo_referenceRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::phidgets::servo_referenceRequest> should match 
// service_traits::DataType< ::phidgets::servo_reference > 
template<>
struct DataType< ::phidgets::servo_referenceRequest>
{
  static const char* value()
  {
    return DataType< ::phidgets::servo_reference >::value();
  }
  static const char* value(const ::phidgets::servo_referenceRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::phidgets::servo_referenceResponse> should match 
// service_traits::MD5Sum< ::phidgets::servo_reference > 
template<>
struct MD5Sum< ::phidgets::servo_referenceResponse>
{
  static const char* value()
  {
    return MD5Sum< ::phidgets::servo_reference >::value();
  }
  static const char* value(const ::phidgets::servo_referenceResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::phidgets::servo_referenceResponse> should match 
// service_traits::DataType< ::phidgets::servo_reference > 
template<>
struct DataType< ::phidgets::servo_referenceResponse>
{
  static const char* value()
  {
    return DataType< ::phidgets::servo_reference >::value();
  }
  static const char* value(const ::phidgets::servo_referenceResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PHIDGETS_MESSAGE_SERVO_REFERENCE_H
