// Generated by gencpp from file phidgets/stepper_params.msg
// DO NOT EDIT!


#ifndef PHIDGETS_MESSAGE_STEPPER_PARAMS_H
#define PHIDGETS_MESSAGE_STEPPER_PARAMS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace phidgets
{
template <class ContainerAllocator>
struct stepper_params_
{
  typedef stepper_params_<ContainerAllocator> Type;

  stepper_params_()
    : header()
    , index(0)
    , engage(false)
    , velocity(0.0)
    , acceleration(0.0)
    , position(0)
    , reset_position(false)  {
    }
  stepper_params_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , index(0)
    , engage(false)
    , velocity(0.0)
    , acceleration(0.0)
    , position(0)
    , reset_position(false)  {
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef int32_t _index_type;
  _index_type index;

   typedef uint8_t _engage_type;
  _engage_type engage;

   typedef float _velocity_type;
  _velocity_type velocity;

   typedef float _acceleration_type;
  _acceleration_type acceleration;

   typedef int64_t _position_type;
  _position_type position;

   typedef uint8_t _reset_position_type;
  _reset_position_type reset_position;




  typedef boost::shared_ptr< ::phidgets::stepper_params_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::phidgets::stepper_params_<ContainerAllocator> const> ConstPtr;

}; // struct stepper_params_

typedef ::phidgets::stepper_params_<std::allocator<void> > stepper_params;

typedef boost::shared_ptr< ::phidgets::stepper_params > stepper_paramsPtr;
typedef boost::shared_ptr< ::phidgets::stepper_params const> stepper_paramsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::phidgets::stepper_params_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::phidgets::stepper_params_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace phidgets

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'nav_msgs': ['/opt/ros/indigo/share/nav_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/indigo/share/sensor_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/indigo/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'move_base_msgs': ['/opt/ros/indigo/share/move_base_msgs/cmake/../msg'], 'phidgets': ['/home/jayme/workspace/dextrus_ws/src/phidgets/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::phidgets::stepper_params_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::phidgets::stepper_params_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::phidgets::stepper_params_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::phidgets::stepper_params_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::phidgets::stepper_params_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::phidgets::stepper_params_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::phidgets::stepper_params_<ContainerAllocator> >
{
  static const char* value()
  {
    return "faf532c364161048d569579c62455339";
  }

  static const char* value(const ::phidgets::stepper_params_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xfaf532c364161048ULL;
  static const uint64_t static_value2 = 0xd569579c62455339ULL;
};

template<class ContainerAllocator>
struct DataType< ::phidgets::stepper_params_<ContainerAllocator> >
{
  static const char* value()
  {
    return "phidgets/stepper_params";
  }

  static const char* value(const ::phidgets::stepper_params_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::phidgets::stepper_params_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
int32 index\n\
bool engage\n\
float32 velocity\n\
float32 acceleration\n\
int64 position\n\
bool reset_position\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::phidgets::stepper_params_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::phidgets::stepper_params_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.index);
      stream.next(m.engage);
      stream.next(m.velocity);
      stream.next(m.acceleration);
      stream.next(m.position);
      stream.next(m.reset_position);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct stepper_params_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::phidgets::stepper_params_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::phidgets::stepper_params_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "index: ";
    Printer<int32_t>::stream(s, indent + "  ", v.index);
    s << indent << "engage: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.engage);
    s << indent << "velocity: ";
    Printer<float>::stream(s, indent + "  ", v.velocity);
    s << indent << "acceleration: ";
    Printer<float>::stream(s, indent + "  ", v.acceleration);
    s << indent << "position: ";
    Printer<int64_t>::stream(s, indent + "  ", v.position);
    s << indent << "reset_position: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.reset_position);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PHIDGETS_MESSAGE_STEPPER_PARAMS_H
