// Generated by gencpp from file phidgets/textlcd_params.msg
// DO NOT EDIT!


#ifndef PHIDGETS_MESSAGE_TEXTLCD_PARAMS_H
#define PHIDGETS_MESSAGE_TEXTLCD_PARAMS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace phidgets
{
template <class ContainerAllocator>
struct textlcd_params_
{
  typedef textlcd_params_<ContainerAllocator> Type;

  textlcd_params_()
    : header()
    , row()
    , contrast(0)
    , cursor(false)
    , blink(false)  {
    }
  textlcd_params_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , row(_alloc)
    , contrast(0)
    , cursor(false)
    , blink(false)  {
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > , typename ContainerAllocator::template rebind<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::other >  _row_type;
  _row_type row;

   typedef int8_t _contrast_type;
  _contrast_type contrast;

   typedef uint8_t _cursor_type;
  _cursor_type cursor;

   typedef uint8_t _blink_type;
  _blink_type blink;




  typedef boost::shared_ptr< ::phidgets::textlcd_params_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::phidgets::textlcd_params_<ContainerAllocator> const> ConstPtr;

}; // struct textlcd_params_

typedef ::phidgets::textlcd_params_<std::allocator<void> > textlcd_params;

typedef boost::shared_ptr< ::phidgets::textlcd_params > textlcd_paramsPtr;
typedef boost::shared_ptr< ::phidgets::textlcd_params const> textlcd_paramsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::phidgets::textlcd_params_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::phidgets::textlcd_params_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace phidgets

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'nav_msgs': ['/opt/ros/indigo/share/nav_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/indigo/share/sensor_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/indigo/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'move_base_msgs': ['/opt/ros/indigo/share/move_base_msgs/cmake/../msg'], 'phidgets': ['/home/jayme/workspace/dextrus_ws/src/phidgets/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::phidgets::textlcd_params_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::phidgets::textlcd_params_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::phidgets::textlcd_params_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::phidgets::textlcd_params_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::phidgets::textlcd_params_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::phidgets::textlcd_params_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::phidgets::textlcd_params_<ContainerAllocator> >
{
  static const char* value()
  {
    return "59746e91d84bf92a93f3c739052658f0";
  }

  static const char* value(const ::phidgets::textlcd_params_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x59746e91d84bf92aULL;
  static const uint64_t static_value2 = 0x93f3c739052658f0ULL;
};

template<class ContainerAllocator>
struct DataType< ::phidgets::textlcd_params_<ContainerAllocator> >
{
  static const char* value()
  {
    return "phidgets/textlcd_params";
  }

  static const char* value(const ::phidgets::textlcd_params_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::phidgets::textlcd_params_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
string[] row\n\
byte contrast\n\
bool cursor\n\
bool blink\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::phidgets::textlcd_params_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::phidgets::textlcd_params_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.row);
      stream.next(m.contrast);
      stream.next(m.cursor);
      stream.next(m.blink);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct textlcd_params_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::phidgets::textlcd_params_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::phidgets::textlcd_params_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "row[]" << std::endl;
    for (size_t i = 0; i < v.row.size(); ++i)
    {
      s << indent << "  row[" << i << "]: ";
      Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.row[i]);
    }
    s << indent << "contrast: ";
    Printer<int8_t>::stream(s, indent + "  ", v.contrast);
    s << indent << "cursor: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.cursor);
    s << indent << "blink: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.blink);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PHIDGETS_MESSAGE_TEXTLCD_PARAMS_H
